// Package ai implements the AI→GlyphLang→Execute pipeline.
// An LLM is prompted to output GlyphLang code, which is then parsed,
// compiled, and executed — making GlyphLang the native output format for AI.
package ai

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/glyphlang/glyph/pkg/ast"
	"github.com/glyphlang/glyph/pkg/compiler"
	"github.com/glyphlang/glyph/pkg/interpreter"
	"github.com/glyphlang/glyph/pkg/llm"
	"github.com/glyphlang/glyph/pkg/parser"
	"github.com/glyphlang/glyph/pkg/vm"
)

// Pipeline orchestrates the AI→GlyphLang→Execute flow.
type Pipeline struct {
	llmHandler *llm.Handler
	model      string
}

// Result holds the output from a pipeline execution.
type Result struct {
	// GlyphCode is the GlyphLang code generated by the AI.
	GlyphCode string
	// Output is the execution result.
	Output interface{}
	// Method describes how the code was executed: "bytecode" or "interpreter".
	Method string
}

// NewPipeline creates a new AI pipeline with the given LLM provider and model.
func NewPipeline(provider, apiKey, model string) *Pipeline {
	return &Pipeline{
		llmHandler: llm.NewHandler(provider, apiKey),
		model:      model,
	}
}

// NewPipelineWithBaseURL creates a pipeline with a custom LLM base URL (e.g., for LM Studio, Ollama).
func NewPipelineWithBaseURL(provider, apiKey, model, baseURL string) (*Pipeline, error) {
	handler, err := llm.NewHandlerWithBaseURL(provider, apiKey, baseURL)
	if err != nil {
		return nil, err
	}
	return &Pipeline{
		llmHandler: handler,
		model:      model,
	}, nil
}

// systemPrompt teaches the LLM to output valid GlyphLang.
const systemPrompt = `You are a GlyphLang code generator. You output ONLY valid GlyphLang code — no markdown, no explanations, no backticks, no code fences.

GlyphLang is a symbol-first backend language. Key syntax:

SYMBOLS:
  @  Route      @ GET /users { ... }
  :  Type       : User { name: str!, age: int! }
  $  Variable   $ x = 42
  !  Function   ! add(a: int, b: int) -> int { > a + b }
  >  Return     > {message: "ok"}
  #  Comment    # this is a comment

TYPES: str, int, float, bool, map, [type] (array)

COMMANDS (for standalone execution):
  @ command run {
    $ x = 10 + 5
    print("Result: " + toString(x))
    > {result: x}
  }

RULES:
- Wrap all executable code in: @ command run { ... }
- Use $ for variable declarations
- Use > for return values (returns a value from the command)
- Use print() for output
- String concatenation uses +
- Use toString() to convert non-strings
- Available builtins: print, toString, toInt, length, typeOf, keys, values
- Output ONLY the GlyphLang code as plain text, nothing else
- NEVER use backticks or code fences / markdown formatting
- Start directly with @ command run { ... }`

// Run prompts the LLM, parses the output as GlyphLang, and executes it.
func (p *Pipeline) Run(prompt string) (*Result, error) {
	// Step 1: Get GlyphLang code from LLM
	code, err := p.generate(prompt)
	if err != nil {
		return nil, fmt.Errorf("generation failed: %w", err)
	}

	// Step 2: Parse the GlyphLang code
	module, err := parse(code)
	if err != nil {
		return nil, fmt.Errorf("parse failed (AI output was not valid GlyphLang):\n%s\n\nCode:\n%s", err, code)
	}

	// Step 3: Execute — try bytecode compilation first, fall back to interpreter
	result, method, err := execute(module)
	if err != nil {
		return nil, fmt.Errorf("execution failed: %w", err)
	}

	return &Result{
		GlyphCode: code,
		Output:    result,
		Method:    method,
	}, nil
}

// RunCode parses and executes pre-written GlyphLang code (no LLM call).
func (p *Pipeline) RunCode(code string) (*Result, error) {
	module, err := parse(code)
	if err != nil {
		return nil, fmt.Errorf("parse failed: %w", err)
	}

	result, method, err := execute(module)
	if err != nil {
		return nil, fmt.Errorf("execution failed: %w", err)
	}

	return &Result{
		GlyphCode: code,
		Output:    result,
		Method:    method,
	}, nil
}

// generate calls the LLM and returns GlyphLang code.
func (p *Pipeline) generate(prompt string) (string, error) {
	resp, err := p.llmHandler.Complete(map[string]interface{}{
		"model": p.model,
		"messages": []map[string]interface{}{
			{"role": "system", "content": systemPrompt},
			{"role": "user", "content": prompt},
		},
		"temperature": 0.2,
		"max_tokens":  2048,
	})
	if err != nil {
		return "", err
	}

	content, ok := resp["content"].(string)
	if !ok {
		return "", fmt.Errorf("unexpected response format: no content field")
	}

	return extractCode(content), nil
}

// extractCode strips markdown fences if the LLM wraps its output.
func extractCode(raw string) string {
	raw = strings.TrimSpace(raw)

	// Strip ```glyph ... ``` or ``` ... ```
	re := regexp.MustCompile("(?s)^```(?:glyph)?\\s*\n?(.*?)\\s*```$")
	if m := re.FindStringSubmatch(raw); len(m) > 1 {
		return strings.TrimSpace(m[1])
	}

	return raw
}

// parse tokenizes and parses GlyphLang source into an AST module.
func parse(source string) (*ast.Module, error) {
	lexer := parser.NewLexer(source)
	tokens, err := lexer.Tokenize()
	if err != nil {
		return nil, fmt.Errorf("lexer error: %w", err)
	}

	p := parser.NewParser(tokens)
	module, err := p.Parse()
	if err != nil {
		return nil, fmt.Errorf("parser error: %w", err)
	}

	return module, nil
}

// execute tries bytecode compilation first (for route-based code),
// then falls back to the interpreter (for commands, functions, etc.).
func execute(module *ast.Module) (interface{}, string, error) {
	// Try bytecode path: compile routes → VM
	for _, item := range module.Items {
		if route, ok := item.(*ast.Route); ok {
			// HTTP routes can be compiled to bytecode
			// Commands (route.Method == 0 and path == "command") use interpreter
			if route.Path != "command" && route.Path != "" {
				c := compiler.NewCompiler()
				bytecode, err := c.CompileRoute(route)
				if err == nil {
					vmInstance := vm.NewVM()
					result, err := vmInstance.Execute(bytecode)
					if err == nil {
						return result, "bytecode", nil
					}
				}
				// Fall through to interpreter on compile/exec failure
			}
		}
	}

	// Interpreter path: handles commands, functions, general code
	interp := interpreter.NewInterpreter()
	if err := interp.LoadModule(*module); err != nil {
		return nil, "", fmt.Errorf("module load failed: %w", err)
	}

	// Try to execute the "run" command (our convention for AI output)
	if cmd, ok := interp.GetCommand("run"); ok {
		result, err := interp.ExecuteCommand(&cmd, map[string]interface{}{})
		if err != nil {
			return nil, "", err
		}
		return result, "interpreter", nil
	}

	// Try to execute "main" command as fallback
	if cmd, ok := interp.GetCommand("main"); ok {
		result, err := interp.ExecuteCommand(&cmd, map[string]interface{}{})
		if err != nil {
			return nil, "", err
		}
		return result, "interpreter", nil
	}

	// If there are routes but no commands, compile first route
	for _, item := range module.Items {
		if route, ok := item.(*ast.Route); ok {
			result, err := interp.ExecuteRouteSimple(route, map[string]string{})
			if err != nil {
				return nil, "", err
			}
			return result, "interpreter", nil
		}
	}

	return nil, "", fmt.Errorf("no executable code found: expected @ command run { ... } block")
}
